name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build, lint, test and publish to NPM

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.7

      - name: Install deps and build (with cache)
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test --ci --coverage

      - name: Build
        run: pnpm build

      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v2.2.1
        with:
          # The NPM access token to use when publishing
          token: ${{ secrets.NPM_SECRET }}
